# NEON AOP Crosswalk Configuration
# Public repository configuration for NEON AOP data integration
# All data referenced here is publicly available through NEON Data Portal

# Global settings
processing:
  target_grids: ["sentinel2_10m", "landsat_30m"]
  resampling_methods: ["average", "bilinear", "cubic"]
  quality_filters:
    cloud_cover_threshold: 20
    data_quality_minimum: 0.8

crosswalk:
  model_types: ["linear", "ensemble"]
  validation:
    test_size: 0.2
    cross_validation_folds: 5
    random_state: 42
  feature_selection:
    correlation_threshold: 0.8
    variance_threshold: 0.01

paths:
  models_root: "data/models/aop_crosswalk"
  processed_data_root: "data/processed/aop"
  outputs_root: "data/outputs/aop_crosswalk"
  logs_root: "logs/aop_crosswalk"

neon_api:
  base_url: "https://data.neonscience.org/api/v0"
  timeout: 30
  max_retries: 3

gee:
  project: "wildfire-risk-prediction"
  asset_collection: "projects/neon-prod-earthengine/assets"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Public NEON AOP sites for crosswalk analysis
# These sites are publicly available and commonly used for research
sites:
  - code: "SRER"
    name: "Santa Rita Experimental Range"
    description: "Desert grassland and shrubland ecosystem in Arizona, excellent for vegetation studies"
    location:
      lat: 31.8214
      lon: -110.8661
      elevation: 1100  # meters
    bounds: [-111.51, 31.74, -111.46, 31.79]  # [minx, miny, maxx, maxy]
    aop_data:
      - year: 2021
        chm_product: "DP3.30024.001"  # Canopy Height Model
        hsi_product: "DP3.30026.001"  # Hyperspectral Reflectance
        rgb_product: "DP3.30010.001"  # RGB Camera Imagery
        lidar_product: "DP1.30003.001"  # Discrete Return LiDAR
        data_path: "data/raw/aop/SRER/2021"
        processed_path: "data/processed/aop/SRER/2021"
      - year: 2022
        chm_product: "DP3.30024.001"
        hsi_product: "DP3.30026.001"
        rgb_product: "DP3.30010.001"
        lidar_product: "DP1.30003.001"
        data_path: "data/raw/aop/SRER/2022"
        processed_path: "data/processed/aop/SRER/2022"
    target_grid: "sentinel2_10m"
    priority: "high"
    research_focus: ["vegetation structure", "biomass estimation", "ecosystem monitoring"]

  - code: "JORN"
    name: "Jornada Experimental Range"
    description: "Chihuahuan Desert ecosystem in New Mexico, important for arid land studies"
    location:
      lat: 32.6147
      lon: -106.7400
      elevation: 1358  # meters
    bounds: [-106.85, 32.55, -106.75, 32.65]
    aop_data:
      - year: 2021
        chm_product: "DP3.30024.001"
        hsi_product: "DP3.30026.001"
        rgb_product: "DP3.30010.001"
        lidar_product: "DP1.30003.001"
        data_path: "data/raw/aop/JORN/2021"
        processed_path: "data/processed/aop/JORN/2021"
    target_grid: "sentinel2_10m"
    priority: "medium"
    research_focus: ["desert ecology", "vegetation change", "climate adaptation"]

  - code: "ONAQ"
    name: "Onaqui Airstrip"
    description: "Sagebrush steppe ecosystem in Utah, representative of western rangelands"
    location:
      lat: 40.4567
      lon: -112.4567
      elevation: 1600  # meters
    bounds: [-112.50, 40.40, -112.45, 40.50]
    aop_data:
      - year: 2021
        chm_product: "DP3.30024.001"
        hsi_product: "DP3.30026.001"
        rgb_product: "DP3.30010.001"
        lidar_product: "DP1.30003.001"
        data_path: "data/raw/aop/ONAQ/2021"
        processed_path: "data/processed/aop/ONAQ/2021"
    target_grid: "sentinel2_10m"
    priority: "medium"
    research_focus: ["rangeland management", "sagebrush ecology", "wildlife habitat"]

  - code: "SJER"
    name: "San Joaquin Experimental Range"
    description: "Oak woodland ecosystem in California, important for Mediterranean climate studies"
    location:
      lat: 37.1089
      lon: -119.7328
      elevation: 400  # meters
    bounds: [-119.75, 37.10, -119.70, 37.15]
    aop_data:
      - year: 2021
        chm_product: "DP3.30024.001"
        hsi_product: "DP3.30026.001"
        rgb_product: "DP3.30010.001"
        lidar_product: "DP1.30003.001"
        data_path: "data/raw/aop/SJER/2021"
        processed_path: "data/processed/aop/SJER/2021"
    target_grid: "sentinel2_10m"
    priority: "medium"
    research_focus: ["oak woodland ecology", "Mediterranean ecosystems", "biodiversity monitoring"]