# NEON AOP product configuration
# Product IDs and specifications for AOP data downloads

# TODO: Verify all product IDs with NEON data portal
# Current IDs are based on NEON documentation but may need updates

aop_products:
  # LiDAR-derived products
  canopy_height_model:
    id: "DP3.30015.001"
    name: "Ecosystem structure - CHM"
    type: "raster"
    format: "GeoTIFF"
    resolution: 1.0  # meters
    units: "meters"
    description: "Canopy height model derived from LiDAR point cloud"
    
  digital_terrain_model:
    id: "DP3.30024.001"
    name: "Elevation - DTM"
    type: "raster"
    format: "GeoTIFF"
    resolution: 1.0
    units: "meters"
    description: "Bare earth elevation model"
    
  digital_surface_model:
    id: "DP3.30024.001"
    name: "Elevation - DSM"
    type: "raster"
    format: "GeoTIFF"
    resolution: 1.0
    units: "meters"
    description: "Top of canopy elevation model"
    
  slope_aspect:
    id: "DP3.30025.001"
    name: "Slope and Aspect"
    type: "raster"
    format: "GeoTIFF"
    resolution: 1.0
    units: "degrees"
    description: "Terrain slope and aspect derived from DTM"
    
  # Hyperspectral products
  hyperspectral_reflectance:
    id: "DP3.30006.001"
    name: "Spectrometer orthorectified surface directional reflectance"
    type: "raster"
    format: "HDF5"
    bands: 426
    wavelength_range: [380, 2510]  # nm
    resolution: 1.0
    units: "reflectance"
    description: "Full hyperspectral cube, atmospherically corrected"
    
  hyperspectral_indices:
    id: "DP3.30026.001"  # TODO: Verify if this exists
    name: "Vegetation indices from hyperspectral"
    type: "raster"
    format: "GeoTIFF"
    resolution: 1.0
    indices: ["NDVI", "EVI", "ARVI", "SAVI", "PRI", "WBI", "NDNI"]
    description: "Pre-calculated vegetation indices"
    
  # Camera products
  high_resolution_camera:
    id: "DP3.30010.001"
    name: "High-resolution orthorectified camera imagery"
    type: "raster"
    format: "GeoTIFF"
    bands: 3  # RGB
    resolution: 0.1  # 10 cm
    units: "DN"
    description: "RGB camera imagery at 10cm resolution"
    
  # Derived products we'll compute
derived_features:
  structure:
    - name: "chm_p10"
      description: "10th percentile canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_p25"
      description: "25th percentile canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_p50"
      description: "Median canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_p75"
      description: "75th percentile canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_p90"
      description: "90th percentile canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_mean"
      description: "Mean canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_std"
      description: "Standard deviation of canopy height"
      source: "canopy_height_model"
      units: "meters"
      
    - name: "chm_cv"
      description: "Coefficient of variation of canopy height"
      source: "canopy_height_model"
      units: "ratio"
      
    - name: "canopy_cover_gt2m"
      description: "Fraction of pixels with canopy > 2m"
      source: "canopy_height_model"
      units: "fraction"
      
    - name: "canopy_cover_gt5m"
      description: "Fraction of pixels with canopy > 5m"
      source: "canopy_height_model"
      units: "fraction"
      
    - name: "canopy_cover_gt10m"
      description: "Fraction of pixels with canopy > 10m"
      source: "canopy_height_model"
      units: "fraction"
      
    - name: "chm_rumple"
      description: "Canopy surface roughness index"
      source: "canopy_height_model"
      units: "ratio"
      
    - name: "chm_entropy"
      description: "Shannon entropy of canopy heights"
      source: "canopy_height_model"
      units: "bits"
      
  spectral:
    - name: "ndvi_aop"
      description: "Normalized Difference Vegetation Index from AOP"
      source: "hyperspectral_reflectance"
      formula: "(NIR - Red) / (NIR + Red)"
      range: [-1, 1]
      
    - name: "evi_aop"
      description: "Enhanced Vegetation Index from AOP"
      source: "hyperspectral_reflectance"
      formula: "2.5 * (NIR - Red) / (NIR + 6*Red - 7.5*Blue + 1)"
      range: [-1, 1]
      
    - name: "savi_aop"
      description: "Soil Adjusted Vegetation Index from AOP"
      source: "hyperspectral_reflectance"
      formula: "1.5 * (NIR - Red) / (NIR + Red + 0.5)"
      range: [-1, 1]
      
    - name: "msavi_aop"
      description: "Modified SAVI from AOP"
      source: "hyperspectral_reflectance"
      formula: "(2*NIR + 1 - sqrt((2*NIR+1)^2 - 8*(NIR-Red))) / 2"
      range: [-1, 1]
      
    - name: "ndwi_aop"
      description: "Normalized Difference Water Index from AOP"
      source: "hyperspectral_reflectance"
      formula: "(Green - NIR) / (Green + NIR)"
      range: [-1, 1]
      
    - name: "mndwi_aop"
      description: "Modified NDWI from AOP"
      source: "hyperspectral_reflectance"
      formula: "(Green - SWIR1) / (Green + SWIR1)"
      range: [-1, 1]
      
    - name: "nbr_aop"
      description: "Normalized Burn Ratio from AOP"
      source: "hyperspectral_reflectance"
      formula: "(NIR - SWIR2) / (NIR + SWIR2)"
      range: [-1, 1]
      
    - name: "nbr2_aop"
      description: "Normalized Burn Ratio 2 from AOP"
      source: "hyperspectral_reflectance"
      formula: "(SWIR1 - SWIR2) / (SWIR1 + SWIR2)"
      range: [-1, 1]
      
    - name: "ndsi_aop"
      description: "Normalized Difference Soil Index from AOP"
      source: "hyperspectral_reflectance"
      formula: "(SWIR1 - Green) / (SWIR1 + Green)"
      range: [-1, 1]
      
  texture:
    - name: "nir_texture_contrast"
      description: "GLCM contrast of NIR band"
      source: "hyperspectral_reflectance"
      window_size: 5
      
    - name: "nir_texture_homogeneity"
      description: "GLCM homogeneity of NIR band"
      source: "hyperspectral_reflectance"
      window_size: 5
      
    - name: "nir_texture_energy"
      description: "GLCM energy of NIR band"
      source: "hyperspectral_reflectance"
      window_size: 5
      
    - name: "nir_texture_correlation"
      description: "GLCM correlation of NIR band"
      source: "hyperspectral_reflectance"
      window_size: 5

# Band definitions for hyperspectral cube
# TODO: Update with actual NEON wavelength-to-band mapping
hyperspectral_bands:
  # Key bands for index calculation
  blue:
    wavelength: 480
    band_index: 48  # TODO: Verify
    bandwidth: 10
    
  green:
    wavelength: 560
    band_index: 67  # TODO: Verify
    bandwidth: 10
    
  red:
    wavelength: 665
    band_index: 90  # TODO: Verify
    bandwidth: 10
    
  red_edge:
    wavelength: 705
    band_index: 100  # TODO: Verify
    bandwidth: 10
    
  nir:
    wavelength: 860
    band_index: 130  # TODO: Verify
    bandwidth: 20
    
  swir1:
    wavelength: 1610
    band_index: 280  # TODO: Verify
    bandwidth: 30
    
  swir2:
    wavelength: 2190
    band_index: 360  # TODO: Verify
    bandwidth: 30

# Download parameters
download:
  max_retries: 3
  chunk_size: 1048576  # 1 MB chunks
  timeout: 300  # seconds
  parallel_downloads: 2
  
# Processing parameters  
processing:
  tile_size: 1000  # Process in 1km x 1km tiles
  overlap: 100  # 100m overlap between tiles
  nodata_value: -9999
  compression: "LZW"
  tiled: true
  blocksize: 256