# NEON AOP Data Products Configuration
# Public repository configuration for NEON AOP data products
# All products referenced here are publicly available through NEON Data Portal

# NEON AOP data products available for crosswalk analysis
data_products:
  # Canopy Height Model (CHM)
  DP3.30024.001:
    name: "Canopy Height Model"
    description: "Raster of canopy height above ground derived from LiDAR"
    units: "meters"
    resolution: 1.0
    format: "GeoTIFF"
    bands: 1
    data_type: "float32"
    no_data_value: -9999
    processing_level: "Level 3"
    citation: "NEON (National Ecological Observatory Network). 2021. Canopy Height Model (DP3.30024.001). https://data.neonscience.org"
    
    # Processing parameters
    processing:
      algorithm: "TCHM"  # Top of Canopy Height Model
      ground_classification: "DP1.30003.001"  # Uses ground points from LiDAR
      smoothing: "Gaussian"
      smoothing_window: 3
      outlier_removal: True
      outlier_threshold: 3.0  # Standard deviations
    
    # Quality metrics
    quality:
      accuracy: 0.5  # meters
      precision: 0.1  # meters
      coverage_threshold: 0.8  # Minimum valid pixel coverage
      validation_method: "Ground truth comparison with field measurements"
    
    # Derived features
    derived_features:
      - "chm_mean"
      - "chm_std"
      - "chm_p10"
      - "chm_p25"
      - "chm_p50"
      - "chm_p75"
      - "chm_p90"
      - "chm_max"
      - "canopy_cover_gt2m"
      - "canopy_cover_gt5m"
      - "rumple_index"
      - "height_entropy"

  # Hyperspectral Reflectance
  DP3.30026.001:
    name: "Hyperspectral Reflectance"
    description: "Calibrated hyperspectral reflectance data from 380-2510nm"
    units: "unitless"
    resolution: 1.0
    format: "HDF5"
    bands: 426
    data_type: "float32"
    no_data_value: -9999
    processing_level: "Level 3"
    citation: "NEON (National Ecological Observatory Network). 2021. Hyperspectral Reflectance (DP3.30026.001). https://data.neonscience.org"
    
    # Processing parameters
    processing:
      atmospheric_correction: "ACORN"
      radiometric_calibration: "Field spectrometer measurements"
      geometric_correction: "GPS/IMU data"
      quality_filtering: "Signal-to-noise ratio > 100"
    
    # Quality metrics
    quality:
      spectral_range: "380-2510 nm"
      spectral_resolution: "5 nm"
      radiometric_accuracy: "±5%"
      geometric_accuracy: "±1 m"
    
    # Derived features
    derived_features:
      - "ndvi_aop"
      - "evi_aop"
      - "nbr_aop"
      - "ndwi_aop"
      - "msavi_aop"
      - "savi_aop"
      - "nbr2_aop"
      - "ndsi_aop"
      - "spectral_mean"
      - "spectral_std"
      - "spectral_min"
      - "spectral_max"

  # RGB Camera Imagery
  DP3.30010.001:
    name: "RGB Camera Imagery"
    description: "High-resolution RGB imagery for visual interpretation"
    units: "unitless"
    resolution: 0.1
    format: "GeoTIFF"
    bands: 3
    data_type: "uint8"
    no_data_value: 0
    processing_level: "Level 3"
    citation: "NEON (National Ecological Observatory Network). 2021. RGB Camera Imagery (DP3.30010.001). https://data.neonscience.org"
    
    # Processing parameters
    processing:
      color_balance: "Automatic white balance"
      geometric_correction: "GPS/IMU data"
      mosaicking: "Seamless stitching"
      compression: "Lossless"
    
    # Quality metrics
    quality:
      spatial_resolution: "10 cm"
      color_accuracy: "±10%"
      geometric_accuracy: "±0.5 m"
    
    # Derived features
    derived_features:
      - "rgb_mean"
      - "rgb_std"
      - "brightness"
      - "contrast"
      - "saturation"

  # Discrete Return LiDAR
  DP1.30003.001:
    name: "Discrete Return LiDAR"
    description: "High-density point cloud data for 3D structure analysis"
    units: "meters"
    resolution: "Point cloud"
    format: "LAS"
    data_type: "float32"
    no_data_value: "N/A"
    processing_level: "Level 1"
    citation: "NEON (National Ecological Observatory Network). 2021. Discrete Return LiDAR (DP1.30003.001). https://data.neonscience.org"
    
    # Processing parameters
    processing:
      point_density: ">8 points/m²"
      classification: "Ground, vegetation, buildings"
      filtering: "Noise removal and outlier detection"
      coordinate_system: "UTM with geoid correction"
    
    # Quality metrics
    quality:
      point_density: "8-15 points/m²"
      vertical_accuracy: "±0.1 m"
      horizontal_accuracy: "±0.5 m"
      classification_accuracy: ">95%"
    
    # Derived features
    derived_features:
      - "point_density"
      - "ground_elevation"
      - "vegetation_height"
      - "canopy_roughness"
      - "vertical_distribution"

# Relationships between products
relationships:
  chm_dependencies:
    - "DP1.30003.001"  # CHM derived from LiDAR
  hsi_calibration:
    - "DP3.30010.001"  # RGB for visual validation
  quality_assessment:
    - "DP3.30010.001"  # RGB for cloud detection
    - "DP1.30003.001"  # LiDAR for ground truth

# Quality control parameters
quality_control:
  cloud_detection:
    method: "RGB threshold + spectral analysis"
    threshold: "20% cloud cover maximum"
  
  data_completeness:
    minimum_coverage: "80%"
    gap_filling: "Interpolation for small gaps"
  
  temporal_consistency:
    max_gap_days: "30 days"
    seasonal_validation: "Field measurements"

# Metadata requirements
metadata:
  required_fields:
    - "site_code"
    - "year"
    - "flight_date"
    - "processing_date"
    - "data_quality_score"
    - "cloud_cover_percentage"
  
  optional_fields:
    - "weather_conditions"
    - "flight_altitude"
    - "sensor_calibration"
    - "ground_control_points"

# Processing workflow
workflow:
  steps:
    1: "Data download from NEON Data Portal"
    2: "Quality assessment and filtering"
    3: "Geometric correction and alignment"
    4: "Feature extraction and analysis"
    5: "Crosswalk model training"
    6: "Validation and assessment"
  
  outputs:
    - "Processed AOP data"
    - "Extracted features"
    - "Trained crosswalk models"
    - "Validation results"
    - "Integration reports"